In [2]:
# NumPy 패키지 설치
! pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ------- -------------------------------- 2.4/12.6 MB 13.5 MB/s eta 0:00:01
   ------------------ --------------------- 5.8/12.6 MB 13.1 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 20.5 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 18.5 MB/s eta 0:00:00



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
# 설치된 NumPy 버전을 출력
import numpy
print(numpy.__version__)

2.2.1


In [7]:
# 리스트로 배열 만들기
import numpy as np

list1 = [1, 2, 3]

arr1 = np.array(list1)

arr1

array([1, 2, 3])

In [8]:
# 5개의 0으로 채워진 배열 만들기
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
# (2, 4) 튜플을 사용해 0으로 초기화된 2차원 배열 만들기
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# 1로 초기화된 배열 생성하기
# 7개의 1로 채워진 배열 만들기
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [11]:
# np.arange 사용하기
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(20, 30, 2)

array([20, 22, 24, 26, 28])

In [14]:
# 랜덤값 배열 만들기
np.random.rand(2, 3)

array([[0.62006808, 0.50580302, 0.62413664],
       [0.95419989, 0.07433548, 0.86890375]])

In [16]:
# 16개의 값이 들어 있는 배열을 (4,4) 형태의 2차원 배열로 변형하기
arr2 = np.arange(16)
arr2.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
# 16개의 값이 들어 있는 배열을 (2, 2, 4) 형태의 배열로 변형하기
arr2 = np.arange(16)
arr2.reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [29]:
# 0부터 9까지 숫자가 담긴 배열 생성
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# 배열의 형태 알아보기
arr.shape

# 10개의 값을 가지는 1차원 배열의 형태임을 확인 가능

(10,)

In [31]:
# 배열에 포함된 데이터의 자료형 알아보기
arr.dtype

# 모든 데이터 타입이 int64로 정수형의 데이터가 들어있음

dtype('int64')

In [34]:
# 배열에 들어 있는 데이터를 실수로 변환하기
arr.astype(float)

# 각각의 데이터가 소수점이 붙어 있는 실수형으로 변환되어 출력

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])